# Generated by Django 4.2.3 on 2023-07-16 10:47

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_lostvehicle_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuser',
            name='mobile',
            field=models.CharField(default=98989898, max_length=26, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cuser',
            name='pincode',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='cuser',
            name='username',
            field=models.CharField(blank=True, error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, null=True, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()]),
        ),
    ]
